---
- name: Install Utils
  hosts: staging-servers
  become: true
  tasks:
    - name: Install Epel Repo
      yum:
        name: 
          - epel-release
        state: present
      tags:
        - epel-release

    - name: Install Utils
      yum:
        name: 
          - htop
          - atop
          - sysstat
          - iotop
          - procps-ng
          - ncdu
        state: present
      tags:
        - utils-setup
    

...