---
# tasks file for nginx
- name: Install Epel Repo
  yum:
    name: epel-release
    state: present
  tags:
    - epel-package
    - packages

- name: Install nginx package
  yum:
    name: nginx
    state: latest
  notify:
    - restart nginx
  tags:
   - nginx-package
   - packages

- name: NGINX | Create NGINX config file from template
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - reload nginx
  tags:
    - nginx-configuration

...